import { defineConfig } from 'vitest/config';
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { unstable_splitSqlQuery } from 'wrangler';

// Pre-read migration SQL and write as a .ts module so tests in the Miniflare
// sandbox can import it (no fs access inside the worker).
const rawNames = readdirSync('./migrations')
  .filter((name: string) => name.endsWith('.sql'))
  .sort((a: string, b: string) => parseInt(a.split('_')[0]) - parseInt(b.split('_')[0]));

const migrations = rawNames.map((name: string) => ({
  name,
  queries: unstable_splitSqlQuery(readFileSync(join('./migrations', name), 'utf8')),
}));

const content = `// Auto-generated by vitest.config.ts — do not edit
export const migrations = ${JSON.stringify(migrations, null, 2)};
`;
writeFileSync('./src/__tests__/migration-data.ts', content);

let poolPlugin: any = undefined;

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts'],
    exclude: ['node_modules', 'client'],
  },
  plugins: [
    {
      name: 'cf-pool-loader',
      enforce: 'pre',
      async config(config) {
        const { cloudflareTest } = await import('@cloudflare/vitest-pool-workers');
        poolPlugin = cloudflareTest({
          wrangler: { configPath: './wrangler.jsonc' },
        });

        if (typeof poolPlugin.config === 'function') {
          const result = poolPlugin.config(config);
          if (result) return result;
        }
      },
      resolveId(id) {
        if (poolPlugin && typeof poolPlugin.resolveId === 'function') {
          return poolPlugin.resolveId(id);
        }
        return null;
      },
      async load(id) {
        if (poolPlugin && typeof (poolPlugin as any).load === 'function') {
          return (poolPlugin as any).load(id);
        }
        return null;
      },
      configureVitest(context: any) {
        if (poolPlugin && typeof poolPlugin.configureVitest === 'function') {
          poolPlugin.configureVitest(context);
        }
      },
    },
  ],
});
