// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	R2_ACCOUNT_ID: "829921384c97e0dbbb34430e307d6b52";
	R2_BUCKET_NAME: "rr33ll-bucket";
	R2_PUBLIC_DOMAIN: "r3l-r2.distorted.work";
	DO_NAMESPACE: DurableObjectNamespace<import("./src/index").RelfDO>;
	BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
