# Top-level configuration
name = "r3l"
main = "./src/index.js"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat", "durable_object_alarms"]

# Serve static assets from the 'public' directory
[site]
bucket = "./public"

# Bindings for services
[[d1_databases]]
binding = "R3L_DB"
database_name = "r3l-db"
database_id = "r3l-db" # Placeholder, wrangler will manage this

[[r2_buckets]]
binding = "R3L_CONTENT_BUCKET"
bucket_name = "r3l-content"

[[kv_namespaces]]
binding = "R3L_KV"
id = "ae72fbc4082047309134b41345a34a9f"

[[kv_namespaces]]
binding = "R3L_SESSIONS"
id = "r3l-R3L_SESSIONS" # Placeholder, wrangler will manage this

[[kv_namespaces]]
binding = "R3L_USER_EMBEDDINGS"
id = "r3l-R3L_USER_EMBEDDINGS" # Placeholder, wrangler will manage this

[[kv_namespaces]]
binding = "R3L_USERS"
id = "r3l-R3L_USERS" # Placeholder, wrangler will manage this

# Durable Object bindings
[durable_objects]
bindings = [
  { name = "R3L_COLLABORATION", class_name = "CollaborationRoom" },
  { name = "R3L_CONNECTIONS", class_name = "ConnectionsObject" },
  { name = "R3L_VISUALIZATION", class_name = "VisualizationObject" },
]

# Environment variables
[vars]
ALLOWED_ORIGINS = "https://r3l.distorted.work"
CONTENT_EXPIRATION_DAYS = 30
D1_DATABASE = "R3L_DB"
KV_NAMESPACE = "R3L_KV"
MAX_UPLOAD_SIZE = 10485760
R2_BUCKET = "R3L_CONTENT_BUCKET"
RATE_LIMIT_REQUESTS = 100
RATE_LIMIT_WINDOW = 60
WORKER_ENV = "production"
# Secrets must be set using `wrangler secret put`
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# JWT_SECRET
# ORCID_CLIENT_ID
# ORCID_CLIENT_SECRET
# R3L_AI_CONTEXT_LIMIT
# R3L_AI_MAX_TOKENS

# Cron Triggers
[triggers]
crons = ["0 */6 * * *"]

# No build configuration needed for pure JS project

# Migration directories for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["CollaborationRoom", "ConnectionsObject", "VisualizationObject"]
