name = "r3l-auth"
compatibility_date = "2025-07-18"

# Use the same KV namespace as the main application
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "ae72fbc4082047309134b41345a34a9f"

# Variables exposed to your Worker
[vars]
GITHUB_REDIRECT_URI = "https://r3l.distorted.work/auth/github/callback"
ORCID_REDIRECT_URI = "https://r3l.distorted.work/auth/orcid/callback"

# Note: Secrets are set using:
# wrangler secret put GITHUB_CLIENT_ID
# wrangler secret put GITHUB_CLIENT_SECRET
# wrangler secret put ORCID_CLIENT_ID
# wrangler secret put ORCID_CLIENT_SECRET
