// Auto-generated by vitest.config.ts — do not edit
export const migrations = [
  {
    "name": "0001_init.sql",
    "queries": [
      "DROP TABLE IF EXISTS users",
      "CREATE TABLE users (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  username TEXT UNIQUE NOT NULL,\n  password TEXT NOT NULL,\n  salt TEXT NOT NULL,\n  avatar_url TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
    ]
  },
  {
    "name": "0002_create_relationship_tables.sql",
    "queries": [
      "CREATE TABLE relationships (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  source_user_id INTEGER NOT NULL,\n  target_user_id INTEGER NOT NULL,\n  type TEXT NOT NULL CHECK(type IN ('asym_follow', 'sym_request')), \n  status TEXT NOT NULL DEFAULT 'accepted' CHECK(status IN ('pending', 'accepted', 'rejected', 'blocked')),\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (source_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE (source_user_id, target_user_id)\n)",
      "CREATE TABLE mutual_connections (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_a_id INTEGER NOT NULL, \n  user_b_id INTEGER NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_a_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (user_b_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE (user_a_id, user_b_id)\n)",
      "CREATE TABLE user_visibility_preferences (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  hidden_user_id INTEGER NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (hidden_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE (user_id, hidden_user_id)\n)"
    ]
  },
  {
    "name": "0003_create_communiques.sql",
    "queries": [
      "-- Migration number: 0003 \t 2025-12-15T00:00:00.000Z\n\n-- Table for user communiques (profiles/dashboards)\nCREATE TABLE communiques (\n  user_id INTEGER PRIMARY KEY,\n  content TEXT DEFAULT '', -- The main text content of the communique\n  theme_prefs TEXT DEFAULT '{}', -- JSON string for theme customization (e.g., accent colors)\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n);\n"
    ]
  },
  {
    "name": "0004_create_files.sql",
    "queries": [
      "CREATE TABLE files (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  r2_key TEXT UNIQUE NOT NULL, \n  filename TEXT NOT NULL,      \n  size INTEGER NOT NULL,       \n  mime_type TEXT,\n  visibility TEXT NOT NULL DEFAULT 'sym' CHECK(visibility IN ('public', 'sym', 'me')),\n  is_archived BOOLEAN DEFAULT 0, \n  expires_at DATETIME NOT NULL,  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_files_expires_at ON files(expires_at) WHERE is_archived = 0"
    ]
  },
  {
    "name": "0005_create_notifications.sql",
    "queries": [
      "CREATE TABLE notifications (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL, \n  actor_id INTEGER,         \n  type TEXT NOT NULL CHECK(type IN ('sym_request', 'sym_accepted', 'file_shared', 'system_alert')),\n  payload TEXT DEFAULT '{}', \n  is_read BOOLEAN DEFAULT 0,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL\n)",
      "CREATE INDEX idx_notifications_user_unread ON notifications(user_id, is_read)"
    ]
  },
  {
    "name": "0006_add_email_to_users.sql",
    "queries": [
      "ALTER TABLE users ADD COLUMN email TEXT",
      "ALTER TABLE users ADD COLUMN is_verified BOOLEAN DEFAULT FALSE",
      "ALTER TABLE users ADD COLUMN verification_token TEXT",
      "CREATE UNIQUE INDEX idx_users_email ON users(email)"
    ]
  },
  {
    "name": "0007_add_vitality_to_files.sql",
    "queries": [
      "ALTER TABLE files ADD COLUMN vitality INTEGER DEFAULT 0"
    ]
  },
  {
    "name": "0008_fix_relationship_constraints.sql",
    "queries": [
      "ALTER TABLE relationships RENAME TO relationships_old",
      "CREATE TABLE relationships (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  source_user_id INTEGER NOT NULL,\n  target_user_id INTEGER NOT NULL,\n  type TEXT NOT NULL CHECK(type IN ('asym_follow', 'sym_request', 'sym_accepted')),\n  status TEXT NOT NULL DEFAULT 'accepted' CHECK(status IN ('pending', 'accepted', 'rejected', 'blocked')),\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (source_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE (source_user_id, target_user_id)\n)",
      "INSERT INTO relationships (id, source_user_id, target_user_id, type, status, created_at, updated_at)\nSELECT id, source_user_id, target_user_id, type, status, created_at, updated_at FROM relationships_old",
      "DROP TABLE relationships_old"
    ]
  },
  {
    "name": "0009_add_user_customization_fields.sql",
    "queries": [
      "ALTER TABLE users ADD COLUMN theme_preferences TEXT DEFAULT '{}'",
      "ALTER TABLE users ADD COLUMN node_primary_color TEXT DEFAULT '#1F77B4'",
      "ALTER TABLE users ADD COLUMN node_secondary_color TEXT DEFAULT '#FF7F0E'",
      "ALTER TABLE users ADD COLUMN node_size INTEGER DEFAULT 8"
    ]
  },
  {
    "name": "0010_create_collections.sql",
    "queries": [
      "CREATE TABLE collections (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    user_id INTEGER NOT NULL,\n    name TEXT NOT NULL,\n    description TEXT,\n    visibility TEXT NOT NULL DEFAULT 'private', \n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n)",
      "CREATE TABLE collection_files (\n    collection_id INTEGER NOT NULL,\n    file_id INTEGER NOT NULL,\n    file_order INTEGER NOT NULL,\n    PRIMARY KEY (collection_id, file_id),\n    FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_collections_user_id ON collections (user_id)",
      "CREATE INDEX idx_collection_files_collection_id ON collection_files (collection_id)",
      "CREATE INDEX idx_collection_files_file_id ON collection_files (file_id)"
    ]
  },
  {
    "name": "0011_create_messages.sql",
    "queries": [
      "CREATE TABLE messages (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  content TEXT NOT NULL,\n  is_read INTEGER DEFAULT 0,\n  created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (sender_id) REFERENCES users(id),\n  FOREIGN KEY (receiver_id) REFERENCES users(id)\n)",
      "CREATE INDEX idx_messages_pair ON messages(sender_id, receiver_id)",
      "CREATE INDEX idx_messages_receiver_read ON messages(receiver_id, is_read)"
    ]
  },
  {
    "name": "0012_add_encryption_and_archive_to_messages.sql",
    "queries": [
      "ALTER TABLE messages ADD COLUMN is_archived INTEGER DEFAULT 0",
      "ALTER TABLE messages ADD COLUMN is_encrypted INTEGER DEFAULT 0",
      "ALTER TABLE messages ADD COLUMN iv TEXT",
      "ALTER TABLE files ADD COLUMN is_encrypted INTEGER DEFAULT 0",
      "ALTER TABLE files ADD COLUMN iv TEXT"
    ]
  },
  {
    "name": "0013_add_parent_id_to_files.sql",
    "queries": [
      "-- Migration number: 0013 \t 2025-12-20T00:00:00.000Z\n\nALTER TABLE files ADD COLUMN parent_id INTEGER REFERENCES files(id) ON DELETE SET NULL;\n"
    ]
  },
  {
    "name": "0014_security_updates.sql",
    "queries": [
      "ALTER TABLE users ADD COLUMN public_key TEXT",
      "ALTER TABLE users ADD COLUMN encrypted_private_key TEXT",
      "ALTER TABLE users ADD COLUMN reset_token TEXT",
      "ALTER TABLE users ADD COLUMN reset_expires DATETIME",
      "ALTER TABLE files ADD COLUMN burn_on_read BOOLEAN DEFAULT FALSE",
      "UPDATE users SET verification_token = lower(hex(randomblob(16))) WHERE verification_token IS NULL"
    ]
  },
  {
    "name": "0015_refinement_phase.sql",
    "queries": [
      "ALTER TABLE files ADD COLUMN tags TEXT",
      "CREATE TABLE IF NOT EXISTS file_keys (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  file_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  encrypted_key TEXT NOT NULL, \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE(file_id, user_id)\n)",
      "CREATE INDEX IF NOT EXISTS idx_files_tags ON files(tags)",
      "CREATE INDEX IF NOT EXISTS idx_file_keys_file_user ON file_keys(file_id, user_id)"
    ]
  },
  {
    "name": "0016_add_missing_indexes.sql",
    "queries": [
      "CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)",
      "CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)",
      "CREATE INDEX IF NOT EXISTS idx_notifications_user_created_at ON notifications(user_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS idx_relationships_source_target_type ON relationships(source_user_id, target_user_id, type)",
      "CREATE INDEX IF NOT EXISTS idx_relationships_target_source_type ON relationships(target_user_id, source_user_id, type)",
      "CREATE INDEX IF NOT EXISTS idx_mutual_connections_users ON mutual_connections(user_a_id, user_b_id)",
      "CREATE INDEX IF NOT EXISTS idx_files_user_visibility_created_at ON files(user_id, visibility, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS idx_files_r2_key ON files(r2_key)",
      "CREATE INDEX IF NOT EXISTS idx_collections_user_id_updated_at ON collections(user_id, updated_at DESC)",
      "CREATE INDEX IF NOT EXISTS idx_collection_files_collection_file ON collection_files(collection_id, file_id)"
    ]
  },
  {
    "name": "0017_performance_indexes.sql",
    "queries": [
      "CREATE INDEX IF NOT EXISTS idx_files_expires_at ON files(expires_at) WHERE is_archived = 0",
      "CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at) WHERE is_archived = 0",
      "CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC)"
    ]
  },
  {
    "name": "0018_message_requests.sql",
    "queries": [
      "ALTER TABLE messages ADD COLUMN is_request INTEGER DEFAULT 0",
      "CREATE INDEX IF NOT EXISTS idx_messages_request ON messages(receiver_id, is_request, created_at)"
    ]
  },
  {
    "name": "0019_group_chat.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS groups (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name TEXT NOT NULL,\n    description TEXT,\n    creator_id INTEGER NOT NULL,\n    visibility TEXT DEFAULT 'private' CHECK(visibility IN ('public', 'sym', 'private')),\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (creator_id) REFERENCES users(id)\n)",
      "CREATE TABLE IF NOT EXISTS group_members (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    group_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    role TEXT DEFAULT 'member' CHECK(role IN ('admin', 'member')),\n    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(group_id, user_id)\n)",
      "CREATE TABLE IF NOT EXISTS group_messages (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    group_id INTEGER NOT NULL,\n    sender_id INTEGER NOT NULL,\n    content TEXT NOT NULL,\n    is_encrypted INTEGER DEFAULT 0,\n    iv TEXT,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,\n    FOREIGN KEY (sender_id) REFERENCES users(id)\n)",
      "CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id)",
      "CREATE INDEX IF NOT EXISTS idx_group_messages_group ON group_messages(group_id, created_at)"
    ]
  },
  {
    "name": "0020_group_sharing.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS group_files (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    group_id INTEGER NOT NULL,\n    file_id INTEGER NOT NULL,\n    shared_by INTEGER NOT NULL,\n    can_edit INTEGER DEFAULT 0,\n    shared_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (shared_by) REFERENCES users(id),\n    UNIQUE(group_id, file_id)\n)",
      "CREATE TABLE IF NOT EXISTS archive_votes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    file_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    vote_weight INTEGER DEFAULT 1,\n    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(file_id, user_id)\n)",
      "ALTER TABLE files ADD COLUMN archive_votes INTEGER DEFAULT 0",
      "ALTER TABLE files ADD COLUMN is_community_archived INTEGER DEFAULT 0",
      "ALTER TABLE groups ADD COLUMN group_type TEXT DEFAULT 'chat' CHECK(group_type IN ('chat', 'sym_group'))",
      "CREATE INDEX IF NOT EXISTS idx_group_files_group ON group_files(group_id)",
      "CREATE INDEX IF NOT EXISTS idx_group_files_file ON group_files(file_id)",
      "CREATE INDEX IF NOT EXISTS idx_archive_votes_file ON archive_votes(file_id)"
    ]
  },
  {
    "name": "0021_message_encryption.sql",
    "queries": [
      "-- Migration: Add encrypted_key column for E2EE messages\nALTER TABLE messages ADD COLUMN encrypted_key TEXT;\n"
    ]
  },
  {
    "name": "0022_feature_gap_fill.sql",
    "queries": [
      "ALTER TABLE users ADD COLUMN is_lurking INTEGER DEFAULT 0",
      "ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'user' CHECK(role IN ('user', 'moderator', 'admin'))",
      "UPDATE users SET role = 'admin' WHERE id = 1"
    ]
  },
  {
    "name": "0023_vitality_votes.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS vitality_votes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    file_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(file_id, user_id)\n)",
      "CREATE INDEX IF NOT EXISTS idx_vitality_votes_file ON vitality_votes(file_id)"
    ]
  },
  {
    "name": "0024_remix_of.sql",
    "queries": [
      "ALTER TABLE files ADD COLUMN remix_of INTEGER REFERENCES files(id) ON DELETE SET NULL",
      "CREATE INDEX IF NOT EXISTS idx_files_remix_of ON files(remix_of)"
    ]
  },
  {
    "name": "0025_last_chance_notified.sql",
    "queries": [
      "-- Add flag to prevent duplicate \"last chance\" notifications per file\nALTER TABLE files ADD COLUMN last_chance_notified INTEGER NOT NULL DEFAULT 0;\n"
    ]
  },
  {
    "name": "0026_create_workspaces.sql",
    "queries": [
      "CREATE TABLE workspaces (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  description TEXT,\n  owner_id INTEGER NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (owner_id) REFERENCES users(id)\n)",
      "CREATE TABLE workspace_members (\n  workspace_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  role TEXT DEFAULT 'member', \n  joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (workspace_id, user_id),\n  FOREIGN KEY (workspace_id) REFERENCES workspaces(id),\n  FOREIGN KEY (user_id) REFERENCES users(id)\n)",
      "ALTER TABLE files ADD COLUMN workspace_id INTEGER REFERENCES workspaces(id)"
    ]
  },
  {
    "name": "0027_relationship_strength.sql",
    "queries": [
      "-- migrations/0027_relationship_strength.sql\nALTER TABLE mutual_connections ADD COLUMN strength INTEGER NOT NULL DEFAULT 1;\n"
    ]
  },
  {
    "name": "0028_archive_votes.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS archive_votes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    file_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(file_id, user_id)\n)",
      "CREATE INDEX IF NOT EXISTS idx_archive_votes_file ON archive_votes(file_id)"
    ]
  },
  {
    "name": "0029_3space_connections.sql",
    "queries": [
      "ALTER TABLE relationships RENAME TO relationships_old",
      "CREATE TABLE relationships (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  source_user_id INTEGER NOT NULL,\n  target_user_id INTEGER NOT NULL,\n  type TEXT NOT NULL CHECK(type IN (\n    'asym_follow',\n    'sym_request',\n    'sym_accepted',\n    '3space_request',\n    '3space_accepted'\n  )),\n  status TEXT NOT NULL DEFAULT 'accepted' CHECK(status IN ('pending', 'accepted', 'rejected', 'blocked')),\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (source_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE(source_user_id, target_user_id)\n)",
      "INSERT INTO relationships (id, source_user_id, target_user_id, type, status, created_at, updated_at)\n  SELECT id, source_user_id, target_user_id, type, status, created_at, updated_at\n  FROM relationships_old",
      "DROP TABLE relationships_old",
      "CREATE INDEX IF NOT EXISTS idx_relationships_source ON relationships(source_user_id)",
      "CREATE INDEX IF NOT EXISTS idx_relationships_target ON relationships(target_user_id)",
      "ALTER TABLE notifications RENAME TO notifications_old",
      "CREATE TABLE notifications (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  actor_id INTEGER,\n  type TEXT NOT NULL CHECK(type IN (\n    'sym_request',\n    'sym_accepted',\n    'file_shared',\n    'system_alert',\n    '3space_request',\n    '3space_accepted'\n  )),\n  payload TEXT DEFAULT '{}',\n  is_read BOOLEAN DEFAULT 0,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL\n)",
      "INSERT INTO notifications (id, user_id, actor_id, type, payload, is_read, created_at)\n  SELECT id, user_id, actor_id, type, payload, is_read, created_at\n  FROM notifications_old",
      "DROP TABLE notifications_old",
      "CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id)",
      "CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id, is_read)"
    ]
  },
  {
    "name": "0030_add_3space_visibility.sql",
    "queries": [
      "ALTER TABLE files RENAME TO files_old",
      "CREATE TABLE files (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  r2_key TEXT UNIQUE NOT NULL,\n  filename TEXT NOT NULL,\n  size INTEGER NOT NULL,\n  mime_type TEXT,\n  visibility TEXT NOT NULL DEFAULT 'sym'\n    CHECK(visibility IN ('public', 'sym', 'me', '3space')),\n  is_archived BOOLEAN DEFAULT 0,\n  expires_at DATETIME NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  vitality INTEGER DEFAULT 0,\n  is_encrypted INTEGER DEFAULT 0,\n  iv TEXT,\n  parent_id INTEGER REFERENCES files(id) ON DELETE SET NULL,\n  burn_on_read BOOLEAN DEFAULT FALSE,\n  tags TEXT,\n  archive_votes INTEGER DEFAULT 0,\n  is_community_archived INTEGER DEFAULT 0,\n  remix_of INTEGER REFERENCES files(id) ON DELETE SET NULL,\n  last_chance_notified INTEGER NOT NULL DEFAULT 0,\n  workspace_id INTEGER REFERENCES workspaces(id),\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n)",
      "INSERT INTO files SELECT * FROM files_old",
      "DROP TABLE files_old",
      "CREATE INDEX IF NOT EXISTS idx_files_expires_at ON files(expires_at) WHERE is_archived = 0",
      "CREATE INDEX IF NOT EXISTS idx_files_user_visibility_created_at ON files(user_id, visibility, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS idx_files_r2_key ON files(r2_key)",
      "CREATE INDEX IF NOT EXISTS idx_files_tags ON files(tags)",
      "CREATE INDEX IF NOT EXISTS idx_files_remix_of ON files(remix_of)"
    ]
  },
  {
    "name": "0031_add_comments.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS comments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,\n  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  parent_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,\n  content TEXT NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
      "CREATE INDEX IF NOT EXISTS idx_comments_file_id ON comments(file_id, created_at)",
      "CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id)"
    ]
  },
  {
    "name": "0032_fix_fk_references.sql",
    "queries": [
      "CREATE TABLE IF NOT EXISTS vitality_votes_new (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    file_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(file_id, user_id)\n)",
      "INSERT OR IGNORE INTO vitality_votes_new SELECT * FROM vitality_votes",
      "DROP TABLE vitality_votes",
      "ALTER TABLE vitality_votes_new RENAME TO vitality_votes",
      "CREATE INDEX IF NOT EXISTS idx_vitality_votes_file ON vitality_votes(file_id)",
      "CREATE TABLE IF NOT EXISTS archive_votes_new (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    file_id INTEGER NOT NULL,\n    user_id INTEGER NOT NULL,\n    vote_weight INTEGER DEFAULT 1,\n    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n    UNIQUE(file_id, user_id)\n)",
      "INSERT OR IGNORE INTO archive_votes_new SELECT * FROM archive_votes",
      "DROP TABLE archive_votes",
      "ALTER TABLE archive_votes_new RENAME TO archive_votes",
      "CREATE INDEX IF NOT EXISTS idx_archive_votes_file ON archive_votes(file_id)",
      "CREATE TABLE IF NOT EXISTS file_keys_new (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  file_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  encrypted_key TEXT NOT NULL,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n  UNIQUE(file_id, user_id)\n)",
      "INSERT OR IGNORE INTO file_keys_new SELECT * FROM file_keys",
      "DROP TABLE file_keys",
      "ALTER TABLE file_keys_new RENAME TO file_keys",
      "CREATE INDEX IF NOT EXISTS idx_file_keys_file_user ON file_keys(file_id, user_id)",
      "CREATE TABLE IF NOT EXISTS collection_files_new (\n    collection_id INTEGER NOT NULL,\n    file_id INTEGER NOT NULL,\n    file_order INTEGER NOT NULL,\n    PRIMARY KEY (collection_id, file_id),\n    FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE\n)",
      "INSERT OR IGNORE INTO collection_files_new SELECT * FROM collection_files",
      "DROP TABLE collection_files",
      "ALTER TABLE collection_files_new RENAME TO collection_files",
      "CREATE INDEX IF NOT EXISTS idx_collection_files_collection_id ON collection_files (collection_id)",
      "CREATE INDEX IF NOT EXISTS idx_collection_files_file_id ON collection_files (file_id)",
      "CREATE TABLE IF NOT EXISTS group_files_new (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    group_id INTEGER NOT NULL,\n    file_id INTEGER NOT NULL,\n    shared_by INTEGER NOT NULL,\n    can_edit INTEGER DEFAULT 0,\n    shared_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,\n    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,\n    FOREIGN KEY (shared_by) REFERENCES users(id),\n    UNIQUE(group_id, file_id)\n)",
      "INSERT OR IGNORE INTO group_files_new SELECT * FROM group_files",
      "DROP TABLE group_files",
      "ALTER TABLE group_files_new RENAME TO group_files",
      "CREATE INDEX IF NOT EXISTS idx_group_files_group ON group_files(group_id)",
      "CREATE INDEX IF NOT EXISTS idx_group_files_file ON group_files(file_id)"
    ]
  }
];
